### DISCUSSION TITLE
Small Caps in KOReader?

### DISCUSSION THREAD

**Discussion by dlgoodr** [koreader/koreader#10238] [Q&A] [answered]
Hello, I have a bit of text in an ePub styled with
```css
.small-caps {
    font-variant: small-caps;
    line-height: 1.2 
    }   
```

This renders well in Marvin on iOS, but does not render in KOReader on my Boox Leaf 2. Is there a way to get small caps in KOReader?

Thanks!
