### DISCUSSION TITLE
Does Koreader support the 'advanced' ebook format of Standard Ebooks?

### DISCUSSION THREAD

**Discussion by ghost** [koreader/koreader#12448] [Q&A]
[standardebooks.org](https://standardebooks.org/ebooks/) offers modern ebooks of public domain literature. Does their 'advanced' format display entirely correctly in Koreader (version `v2024.07` at the time of writing)?

[example book page](https://standardebooks.org/ebooks/charles-dickens/a-christmas-carol)

>**Advanced epub**
>
>An advanced format that uses the latest technology not yet fully supported by most ereaders.

https://standardebooks.org/help/how-to-use-our-ebooks#which-file-to-download

> The **advanced epub** files are not yet suitable for general use. They use the latest technology that isn’t yet supported by most ereaders, so they’re best used as benchmarks for developers working on ereading systems, or for advanced ereaders like ones based on the [Readium toolkit](https://readium.org/awesome-readium/), instead of for the general reading public.

---

It may be necessary to look at the plaintext EPUB file source(s) [or their Github pages](https://github.com/standardebooks/), since their documentation obviously is very sparse.

**Comment by Frenzie** [comment]
Since they mention a browser engine the simple answer is no.

The more complicated answer is that at a glance many of the things it's doing are supported regardless, but controlled by the user or done automatically and not by the book.

```css
body{
	font-variant-numeric: oldstyle-nums;
	hyphens: auto;
	-epub-hyphens: auto;
	text-wrap: pretty;
}
```

```css
/* Invert images in dark mode. RMSDK requires a target media as well as a state. */
@media all and (prefers-color-scheme: dark){
	img[epub|type~="se:image.color-depth.black-on-transparent"]{
		filter: invert(100%);
	}

	img[epub|type~="se:image.color-depth.black-on-transparent"][epub|type~="se:image.style.realistic"]{
		background: currentColor;
		filter: none;
	}
}
```
