### ISSUE TITLE
Strange schrödinger's CSS issue

### ISSUE THREAD

**Issue by NiLuJe** [koreader/koreader#11235]
* KOReader version: 675f5a062
* Device: Kobo/Emu

#### Issue

I've got a couple of books from the same house with apparently benign CSS that appears to just get ignored, unless I apply some specific styles tweaks (e.g., Ignore widow & orphans).

I've attached a reduced testcase here (*rename* to epub).

[test.zip](https://github.com/koreader/koreader/files/13694344/test.zip)

You'll want to disable the default styletweaks to test, as the footnote ones *also* appear to "fix" it ;).

No styletweaks: 
![test_broken](https://github.com/koreader/koreader/assets/111974/a7704f70-cb65-44f6-811e-7dad74125fe5)

Ignore publisher widow & orphan:
![test_plus_styletweaks](https://github.com/koreader/koreader/assets/111974/52e43227-226c-4033-b3ba-c6d5f7f01008)

**Comment by NiLuJe** [comment]
Ah. Apparently a regression, as it appears to behave on the 2023.10 AppImage...

**Comment by NiLuJe** [comment]
As far as @benoit-pierre's branch goes, the first bad artifact is https://github.com/benoit-pierre/koreader/actions/runs/6938994494 (the previous one, https://github.com/benoit-pierre/koreader/actions/runs/6720608996 is good).

**Comment by NiLuJe** [comment]
Ping @bbshelper as your PRs probably fall in that timeframe ;).

**Comment by poire-z** [comment]
> unless I apply some specific styles tweaks (e.g., Ignore widow & orphans).

Seems you need to apply a styletweak targeting `*` for this to solve the issue.
If you use one that doesn't (ie. `Misc> List items> Force bullets`, targetting `ul>li`), it doesn't.

Oh, and somehow, we just need one target of `*`, anywhere, for all of them to work.
```css
p.body-text {
    line-height: 1.14em;
    font-size: 0.88em;
    text-indent: 1em;
}

* { color: blue; }  /* makes them all work ! */
.zzz { color: blue; } /* also works with this one */

p.body-text-opening {
    line-height: 1.14em;
    font-size: 0.88em;
    text-indent: 0;
}

p.ch {
...
```
I'm going to suspect https://github.com/koreader/crengine/pull/545 and something related to the if/else branches around https://github.com/koreader/crengine/pull/545#discussion_r1375305800 .
