### ISSUE TITLE
KOReader shows text in epubs which should be hidden

### ISSUE THREAD

**Issue by beedaddy** [koreader/koreader#11377]
* KOReader version: 2024.01
* Device: Kobo Clara 2E (as well as Linux)

#### Issue
The German newspaper "Die Zeit" (EPUB-version) hides some elements which are only meant for screen-readers, not for displaying on eInk-Devices. The CSS in that case looks like this:
```css
.sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width:0
}
```
The Kobo Nickel reader as well as the Calibre ebook-viewer do not display the text in `<span class="sr-only">Hier gibt es eine Bildunterschrift:</span>`, but KOReader does:
![Bildschirmfoto vom 2024-01-17 07-55-08](https://github.com/koreader/koreader/assets/3264939/5c69c245-7428-4c2a-9409-521becce71c2)

The CSS seems to be ignored. I've attached a minimal example epub.

#### Steps to reproduce
- Extract the attached [test.zip](https://github.com/koreader/koreader/files/13959834/test.zip) file. It contains the example epub.
- Open the example epub. 
- You should not see the hidden line. But KOReader does show it.
