### ISSUE TITLE
Way too slow on PocketBook Touch HD, older version may be better but which?

### ISSUE THREAD

**Issue by kojinmalia** [koreader/koreader#11465]
So i got a touch HD and after the (ultra) long epub loading, it appears, it just loads page 3 by 3. After reading the 3rd, it takes 10-15sec to load the next 3. This is just.. Not ok. Device is certainly slow but i'm sure there are ways to make this better. Tell me please? :)

**Comment by offset-torque** [comment]
Can you confirm this slowness with this book:
 [Alice's Adventures in Wonderland by Lewis Carroll-Direct link](https://www.gutenberg.org/ebooks/11.epub3.images)

If the direct link above doesn't work, here is the book's page on Gutenberg. Please choose the EPUB3 version (first EPUB one): [Alice's Adventures in Wonderland by Lewis Carroll-Gutenberg page](https://www.gutenberg.org/ebooks/11)

So we can narrow down the problem by ruling out the broken EPUB variable.

**Comment by kojinmalia** [comment]
No such issue with that Alice epub. My ebook is much larger than this one
though. Not sure if there's a link. And in the end, is there a fix?

Le mer. 14 févr. 2024 à 09:32, offset-torque ***@***.***> a
écrit :

**Comment by kojinmalia** [comment]
Fix it with calibre ok but how?

Le dim. 18 févr. 2024 à 17:36, offset-torque ***@***.***> a
écrit :

**Comment by Frenzie** [comment]
> I have never experienced any kind of slowness up to around thousand page range. Is there some special bug/case with these PocketBooks?

The number of pages doesn't really matter btw (up to a point). It's the number of elements and the CSS rules that matter.

@kojinmalia Using the ScrambleEbook plugin you can share the file here: https://www.mobileread.com/forums/showthread.php?t=267998

**Comment by poire-z** [comment]
> can you have a look at this case

A look at what ? :)
There is no sample document (and which format, epub or pdf) ? (fortunately, half of the issues are about PDF, so I can ignore them :))
I also never got such behaviour, so I would add it to the Pocketbook pile of strange things.
Also, a crash.log could help noticing what happens between page turn.

**Comment by kojinmalia** [comment]
Am I supposed to share the file on that thread? Làst post was in 2022..

Le dim. 18 févr. 2024 à 17:50, Frans de Jonge ***@***.***> a
écrit :

**Comment by poire-z** [comment]
No, share the file here.
If the file is copyrighted, you can use the tool on that thread to create a scrambled/obfuscated version of that book with the text replaced by garbage (which will be ok for us to investigate).

The only reason I can think of for slow page turning is when there are huge tables spanning multiple pages (Select some text on the page and use View HTML to see if there are any `<table>` - some bad publishers may wrap whole chapters in a single `<table>`). So check that yourself first.

**Comment by kojinmalia** [comment]
Well, when i open it with calibre on computer, it looks fine, just like in the KOBO app (the original), but with other apps (on Android basically), it's completely different.. and broken. KOreader gives the less horrible results. Here's the scambled file : https://file.io/FI7JuvxOJWBG

**Comment by poire-z** [comment]
How the horror !
12900 CSS declarations:
```css
@font-face{font-family:ffbb;src:url(fonts/fbb.ttf)format("truetype");}.ffbb{font-family:ffbb;line-height:1.091309;font-style:normal;font-weight:normal;visibility:visible;}
@font-face{font-family:ffbc;src:url(fonts/fbc.ttf)format("truetype");}.ffbc{font-family:ffbc;line-height:1.178000;font-style:normal;font-weight:normal;visibility:visible;}
[...]
.m4df{transform:matrix(-0.491588,0.000000,0.000000,0.491588,0,0);-ms-transform:matrix(-0.491588,0.000000,0.000000,0.491588,0,0);-webkit-transform:matrix(-0.491588,0.000000,0.000000,0.491588,0,0);}
.m1{transform:matrix(-0.343570,-0.344872,0.393159,-0.295101,0,0);-ms-transform:matrix(-0.343570,-0.344872,0.393159,-0.295101,0,0);-webkit-transform:matrix(-0.343570,-0.344872,0.393159,-0.295101,0,0);}
[...]
.x93{left:874.208729px;}
.x212{left:877.448687px;}
.x1d6{left:878.994436px;}
.x3f{left:881.129894px;}
.x29{left:884.826636px;}
.x224{left:886.321063px;}
```

Tons of classnames (`<div class="t m10 xc5 h33 y1f53 ffb0 fs26 fc0 sc0 ls1 ws1">ixtyzcbxwwp qk p`).
Thousands of `<span>`.
Mostly everything `position: absolute`.
Which explains the superslow loading (60s on my emulator), and possibly the page turn - and the ugly rendering.

I think this is a "fixed layout" EPUB (aimed at looking like a PDF), that not many "normal" eReaders or apps support. Even in my small size Calibre, it looks ugly - even when put full screen..
KOReader surely doesn't (and looking at the kind of input crap we'd have to deal with, even if in the past I thought it could be doable, I'm now convinced that we'll never support that :))

> Device is certainly slow but i'm sure there are ways to make this better. Tell me please? :)

You'd have better luck finding a PDF version of that book :)
