### ISSUE TITLE
incorrect fonts in Debian builds

### ISSUE THREAD

**Issue by jtracey** [koreader/koreader#13509]
* KOReader version: d799468a80c15dae2b0feb43b011f7e7573aa4ce and 2024.11
* Device: Debian

#### Issue

When running koreader as packaged for Debian, I'm running into some epub font problems. Best I can tell, the wrong font is being used when DroidSansFallback.ttf is used in place of DroidSansMono.ttf and the epub provides its own mono font, but the exact cause isn't clear to me so that could be wrong.

#### Steps to reproduce

The epub in question can be purchased from [no starch press](https://nostarch.com/rust-rustaceans). A PDF of the first chapter is available for free, but no free sample epub unfortunately. The CSS for the epub starts with a slightly modified ["Reset CSS"](http://meyerweb.com/eric/tools/css/reset/), then defines the embedded fonts
```css
@font-face {
    font-family: "NSAnnotations-Mono";
    font-style: normal;
    font-weight: normal;
    src: url(image_fi/book_art/NSAnnotations-Mono.otf)
    }
@font-face {
    font-family: "NSAnnotations500-Mono";
    font-style: normal;
    font-weight: normal;
    src: url(image_fi/book_art/NSAnnotations500-Mono.otf)
    }
```
These fonts are only intended to be used for numeric annotations, e.g.
```css
span.CodeAnnotationHang {
    font-family: NSAnnotations-Mono;
    margin-left: -1.5em
    }
```
```xml
<pre><code>...
<span class="CodeAnnotationHang" aria-label="annotation1">1</span> var2 = &amp;y;</code></pre>
```

However, in the Debian version of koreader, the font seems to be used for all monospace fonts, when it should be using the default
```css
code, var {
    font-family: monospace;
    font-size: inherit
    }
```
```xml
Here, there are four distinct values: <code>42</code> (an <code>i32</code>)
```

Debian packaged (bad) rendering:

![Image](https://github.com/user-attachments/assets/e8a34f4d-c664-458b-824a-185a4f85e928)

Generic Linux build (good) rendering:

![Image](https://github.com/user-attachments/assets/be00c43f-bdcf-45ba-aee2-5fc8cde757d5)

The presumably correct rendering can be found in the [sample PDF](https://nostarch.com/download/samples/RustforRustaceans_Ch1.pdf) at the end of page 2/top of page 3 (tl;dr: the generic linux rendering is much closer). The encircled numbers are the most glaring problem, but if you look closely, the entire `<pre><code>` block is using the wrong font (e.g., the & is too curvey for either possible default monospace font).

I was able to get the Debian build to work by commenting out the [line in the packaging script](https://github.com/koreader/koreader/blob/d799468a80c15dae2b0feb43b011f7e7573aa4ce/platform/linux/do_debian_package.sh#L116) that replaces DroidSansMono.ttf with a symlink to DroidSansFallback.ttf, or by replacing the target of the symlink with DroidSansMono.ttf (a good workaround until this is fixed), so this seems to be behavior that occurs whenever DroidSansFallback.ttf is used as the default monospace font, best I can tell. Presumably, the fallback font usage should be transparent (other than the literal differences between the two fonts, of course), so this seems like a bug.
