### ISSUE TITLE
I cant open epub files (created frome html- by "Save as eBook" Chrome extension")

### ISSUE THREAD

**Issue by ocra98** [koreader/koreader#5226]
* KOReader version: v2019.08
* Device: likebook mars t80D, android 6.0.1

#### Issue
Cant open epub file (~6mB); or very slow (5-6s) with small epub file (400kb). See attached file (zip).
This is "Save as eBook" extension i'm using: [https://github.com/alexadam/save-as-ebook](https://github.com/alexadam/save-as-ebook)

[i cant open this epub file- sample.zip](https://github.com/koreader/koreader/files/3516264/i.cant.open.this.epub.file-.sample.zip)

**Comment by Frenzie** [comment]
The smaller EPUB seems to open quickly enough for me, but the larger one definitely takes a while. It's almost certainly the CSS, which looks absurdly complex. 4.4 MB worth of it!

**Comment by poire-z** [comment]
On the small one, which only has 240 CSS classes and only a hundred of node, it still takes 2 seconds on the emulator for applying styles:
```
2019/08/19 16:57:48.2861 TRACE CSS file href: OEBPS/style/style7638.css
2019/08/19 16:57:48.2862 DEBUG Setting StyleSheet attribute to OEBPS/style/style7638.css for document fragment
2019/08/19 16:57:48.2862 TRACE ldomNode::applyNodeStylesheet()
<2s pause here>
2019/08/19 16:57:50.4990 DEBUG Loaded font
```

If I keep the 240 classes, but make their properties smaller, eg just one property, it loads fast:
```
2019/08/19 17:03:12.7378 TRACE CSS file href: OEBPS/style/style7638.css
2019/08/19 17:03:12.7379 DEBUG Setting StyleSheet attribute to OEBPS/style/style7638.css for document fragment
2019/08/19 17:03:12.7379 TRACE ldomNode::applyNodeStylesheet()
2019/08/19 17:03:12.7410 DEBUG Loaded font 
```
I checked with some additional logs that it's really the parsing of that not-that-huge style7638.css that is taking time:
```
2019/08/19 17:11:46.3221 WARN parsing start
2019/08/19 17:11:48.5118 WARN parsing end
```
We may have some issue with the parsing of border* properties, as changing the 240 classes to that:
```css
 .class-24960 {background-color:black;
     zzborder:0px none black;
     zzborder-top:0px none black;
     zzborder-right:0px none black;
     zzborder-bottom:0px none black;
     zzborder-left:0px none black;
color:black;
font:normal normal 400 normal 12px / 12px Arial, sans-serif;
font-size:12px;
font-weight:400;
font-family:Arial, sans-serif;
letter-spacing:0;
line-height:12px;
list-style:disc outside none;
outline:black none 0px;
padding:0px;
text-decoration:none solid black;
text-transform:none;
word-spacing:0px;
}
```
make it loads fast again:
```
2019/08/19 17:23:37.6766 WARN parsing start
2019/08/19 17:23:37.6839 WARN parsing end
```
(I changed the colors set as `rgb(0,1,2)` to "black" in the above snippet, but color was not the cause of the slowness).

On the big one:
```
2019/08/19 17:30:10.8073 WARN parsing start
2019/08/19 17:31:04.6492 WARN parsing end
2019/08/19 17:31:04.7285 WARN parsing start
2019/08/19 17:31:27.0381 WARN parsing end

```(and 8 more to go...)
