### ISSUE TITLE
Hide default fonts in test document

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#6107]
* KOReader version: 2020.04.1-12
* Device: KA1

A request to create an option to hide the default fonts from appearing in the Font menu,
such as Droid Sans Mono, Free Sans, Noto Sans, etc.

I'm testing different typefaces to see how they appear on e-ink. Was hoping there was a way to hide some unused fonts. I can't delete them because they are used by the system.

However it's not an issue.

**Comment by pazos** [comment]
@CalbertAmu 

I didn't notice your edition.

> I'm testing different typefaces to see how they appear on e-ink. Was hoping there was a way to hide some unused fonts. I can't delete them because they are used by the system.

disable default fonts on test document sounds good!

> A request to create an option to hide the default fonts from appearing in the Font menu

Here my reaction to https://github.com/koreader/koreader/issues/6107#issue-610583384 :smile:

**Comment by poire-z** [comment]
> disable default fonts on test document sounds good!

Whether in the menu or the test document, it's a bit too user specific to bother making that an option.
You might not want to see all our shipped fonts, but I might still want to see NotoSerif - and an arabic reader would not care, like us, about NotoSansCJK, but might want to see NotoSansArabic...

But for the font test document, you can help yourself with a user styletweak:
```css
#Droid_Sans_Mono, #Droid_Sans_Mono + div,
#Noto_Sans_Arabic_UI, #Noto_Sans_Arabic_UI + div,
#Noto_Sans_Devanagari_UI, #Noto_Sans_Devanagari_UI + div,
#Noto_Sans_CJK_SC, #Noto_Sans_CJK_SC + div,
#Dummy_that_should_not_get_a_comma_at_the_end
{ display: none; }
```
Apply that once to your `font-test.html`, and it will keep working when you regenerate it.
