### ISSUE TITLE
KOReader crash everytime when reading this book

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#6215]
* KOReader version: v2020.05
* Device: Hisense A5

#### Issue
KOReader crash every time when reading this book. The book can be downloaded by this link:
https://drive.google.com/file/d/1Q-TmUrek05xUnWWv0FoYg-ue14nM1mSS/view?usp=sharing
This book seems to use the newest or irregular layout technology. I don't know about this technology. Its original format is azw3 which is from kindle store. I purchased it and converted it into epub used a tool called KindleUnpack.
This book can be viewed in Kindle app or Google playbook app without any problem, the layout is correct and good.
Other reader apps, such as AlReader, FBReader, MoonPlus reader, all failed at showing the correct layout of the book. They seem missing all the image and the text is very huge and unreadable.
When I use calibre to convert this book from azw3 to epub. It lost all the text in the output epub file. The epub only has images of this book when I view this book, all text seems lost. The only way I found to convert it to epub is using KindleUnpack.

#### Steps to reproduce
1. Open this book in KOReader
2. It shows the title page, everything seems OK
3. Then turn to the next page, KOReader crash

##### `crash.log` (if applicable)
05-31 09:24:39.748 20485 20502 I KOReader:  opening file /storage/emulated/0/doc/new/Julius Zebra_ Rumble with the Romans! - Gary Northfield.epub
05-31 09:24:39.837 20485 20502 I KOReader:  RD loaded plugin batterystat at plugins/batterystat.koplugin
05-31 09:24:39.837 20485 20502 I KOReader:  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
05-31 09:24:39.837 20485 20502 I KOReader:  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
05-31 09:24:39.837 20485 20502 I KOReader:  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
05-31 09:24:39.838 20485 20502 I KOReader:  RD loaded plugin evernote at plugins/evernote.koplugin
05-31 09:24:39.838 20485 20502 I KOReader:  RD loaded plugin goodreads at plugins/goodreads.koplugin
05-31 09:24:39.839 20485 20502 I KOReader:  RD loaded plugin movetoarchive at plugins/movetoarchive.koplugin
05-31 09:24:39.841 20485 20502 I KOReader:  RD loaded plugin statistics at plugins/statistics.koplugin
05-31 09:24:39.841 20485 20502 I KOReader:  RD loaded plugin systemstat at plugins/systemstat.koplugin
05-31 09:25:07.970  1124  7235 I ActivityManager: Process org.koreader.launcher (pid 20485) has died: fore TOP 
05-31 09:25:07.974  1124  7235 W ActivityManager: Force removing ActivityRecord{a5f6c39 u0 org.koreader.launcher/.MainActivity t521}: app died, no saved state
05-31 09:25:08.051  1124  1191 W ActivityManager: setHasOverlayUi called on unknown pid: 20485
05-31 09:25:09.067  1124  4514 W ActivityManager: Background start not allowed: service Intent { cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService } to com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService from pid=19616 uid=10172 pkg=com.google.android.apps.messaging startFg?=false
05-31 09:25:09.072  1124  4514 W ActivityManager: Background start not allowed: service Intent { cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService } to com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService from pid=19616 uid=10172 pkg=com.google.android.apps.messaging startFg?=false

**Comment by poire-z** [comment]
It crashes while dealing with an image on some of the first pages:
```
Thread 1 "luajit" received signal SIGSEGV, Segmentation fault.
0x00007fffecb95648 in CLZWDecoder::WriteOutString (code=0, this=<optimized out>) at /koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvimg.cpp:1295
1295             rev_buf[pos++] = str_table[code];
(gdb) bt
#0  0x00007fffecb95648 in CLZWDecoder::WriteOutString (code=0, this=<optimized out>) at /koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvimg.cpp:1295
#1  CLZWDecoder::Decode (init_code_size=8, this=0x7fffffff7c00) at /koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvimg.cpp:1455
#2  LVGifFrame::DecodeFromBuffer (this=0x55555784cb80, buf=<optimized out>, buf_size=<optimized out>, bytes_read=@0x7fffffffc4bc: 0)
    at /koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvimg.cpp:1591
```
It's around some recent fixe of mine https://github.com/koreader/crengine/commit/2cd6cdb778481c4c1c1669d98d5aedfd1a61ec6c - but it crashes too if I remove it.

But your book is really a mess:
<kbd>![image](https://user-images.githubusercontent.com/24273478/83345219-e41afe80-a310-11ea-8049-7cddd386503d.png)</kbd>
It uses really big font sizes.
And `position: absolute`, so it must be some kind of "fixed layout" EPUB, that no reader really support (except may be those big names readers you mentionned from Kindle or Google). No plan to support this, as it's really something different than regular EPUBs.

```xml
<?xml version="1.0" encoding="utf-8"?>
<package version="3.0"...>
[...]
<meta name="fixed-layout" content="true" />
<meta name="orientation-lock" content="portrait" />
<meta name="original-resolution" content="730x1126" />
<!-- EPUB3 MedaData converted from EXTH -->
<meta property="rendition:layout">pre-paginated</meta>
<meta property="rendition:orientation">portrait</meta>
```
It does not even look allright (absolute positionning at left=9000px where width=730px):
```html
<body style="margin:0;background-color:#808080;width:730px;height:1126px;">
<div id="Page" class="PageContainer" style="position:absolute;top:0px;left:0px;width:730px;height:1126px;">
<div id="ImageContainer4">
</div>
<div class="TextContainer">
<span class="s1 f1 fs1 l0" style="left:8274.43px;bottom:25392.3px;letter-spacing:36.9px;color:rgb(8,9,9);">De</span>
<span class="s1 f1 fs1 l0" style="left:8947.2px;bottom:25392.3px;letter-spacing:36.9px;color:rgb(8,9,9);">d</span>
<span class="s1 f1 fs1 l0" style="left:9265.92px;bottom:25392.3px;letter-spacing:36.9px;color:rgb(8,9,9);">i</span>
<span class="s1 f1 fs1 l0" style="left:9410.3px;bottom:25392.3px;letter-spacing:36.9px;color:rgb(8,9,9);">ca</span>
<span class="s1 f1 fs1 l0" style="left:9946.37px;bottom:25392.3px;letter-spacing:36.9px;color:rgb(8,9,9);">t</span>
<span class="s1 f1 fs1 l0" style="left:10154.5px;bottom:25392.3px;letter-spacing:36.9px;color:rgb(8,9,9);">e</span>
<span class="s1 f1 fs1 l0" style="left:10473.2px;bottom:25392.3px;letter-spacing:36.9px;word-spacing:1.5px;color:rgb(8,9,9);">d t</span>
```

```css
#ImageContainer2
{
        background-image: url(../Images/image00539.gif);
        background-size: 730px 1126px;
        position:absolute;
        width:730px;
        height:1126px;
}
```

I'll look at having it not crash on one of these images - so at least you can see how crappy the book is :)
One image that makes it crash is this large blank image [image00539.zip](https://github.com/koreader/koreader/files/4707183/image00539.zip)


```
   4144 May 30 22:56 image00539.gif
image00539.gif: GIF image data, version 89a, 1394 x 2151
```

But not much else we can do.

Anyway, you can get a grasp of this book by disabling Embedded Styles (rightmost panel in bottom config menu) - before you reach a page where it crash. One paragraph per page, with some space inside words...

**Comment by Frenzie** [comment]
I can confirm a segmentation fault after turning the page.

```
Segmentation fault
*** Segmentation fault
Register dump:

 RAX: 0000000000000000   RBX: 0000565474f320b0   RCX: 0000000000000903
 RDX: 0000000000006654   RSI: 0000000000000902   RDI: 0000000000000009
 RBP: 00007ffdcf0c51e0   R8 : 0000000000000101   R9 : 0000000000000102
 R10: 0000000000006655   R11: 0000000000000000   R12: 0000565473564370
 R13: 0000000000000001   R14: 0000565474f31390   R15: 0000000000000100
 RSP: 00007ffdcf0c0970

 RIP: 00007fca60608cd3   EFLAGS: 00010246

 CS: 0033   FS: 0000   GS: 0000

 Trap: 0000000e   Error: 00000006   OldMask: 00000000   CR2: cf0c9000

 FPUCW: 0000037f   FPUSW: 00000000   TAG: 00007fca
 RIP: 93427ffd   RDP: cf0c6258

 ST(0) 0000 0000000000000000   ST(1) 0000 0000000000000000
 ST(2) 0000 0000000000000000   ST(3) 0000 0000000000000000
 ST(4) 0000 0000000000000000   ST(5) ffff c000000000000000
 ST(6) ffff bda68e2c00000000   ST(7) e100 e100000000000000
 mxcsr: 1fa5
 XMM0:  0000000000000000000000000002a300 XMM1:  0000000000000000000000000002a300
 XMM2:  0000000000000000000000000002a300 XMM3:  0000000000000000000000000002a300
 XMM4:  0000000000000000000000000002a300 XMM5:  0000000000000000000000000002a300
 XMM6:  0000000000000000000000000002a300 XMM7:  0000000000000000000000000002a300
 XMM8:  0000000000000000000000000002a300 XMM9:  0000000000000000000000000002a300
 XMM10: 0000000000000000000000000002a300 XMM11: 0000000000000000000000000002a300
 XMM12: 0000000000000000000000000002a300 XMM13: 0000000000000000000000000002a300
 XMM14: 0000000000000000000000000002a300 XMM15: 0000000000000000000000000002a300

Backtrace:
/home/frans/src/kobo/koreader/koreader-emulator-x86_64-linux-gnu-debug/koreader/libs/libcrengine.so(_ZN10LVGifFrame16DecodeFromBufferEPhiRi+0x773)[0x7fca60608cd3]
```

That looks fairly self-explanatory even without deeper investigation. At least one of the GIFs in that file does something unexpected to the code [here](https://github.com/koreader/crengine/blob/3ad652ce69d941e9f7e50a5b9dedad3111432f50/crengine/src/lvimg.cpp).

To find out where it goes wrong I'd have to check with gdb and I don't have time for that right this moment, but posting to help others forward.
