### ISSUE TITLE
Furigana support

### ISSUE THREAD

**Issue by Geniusssmit** [koreader/koreader#6223]
* KOReader version: May
* Device: pocketbook 740

#### Issue
Furigana is rendered after kanji but not above them which makes it harder to read and impossible to use dictionaries

**Comment by NiLuJe** [comment]
You're going to to have to give more details and examples, for those of us who happen to be CJK-challenged ;).

**Comment by Geniusssmit** [comment]
this is how furigana should look like 
![image](https://user-images.githubusercontent.com/24941285/83559592-7db6fb80-a51d-11ea-83fe-ea4c1c19e4ed.png)
This is how furigana looks currently
躊躇ためらう

**Comment by Geniusssmit** [comment]
Or that
![image](https://user-images.githubusercontent.com/24941285/83559720-b9ea5c00-a51d-11ea-9bf5-8aea3a439803.png)
looks like that
融ゆう通づう
(furigana after each kanji separately)

**Comment by poire-z** [comment]
Technically, that doesn't happen automagically with any text.
Your source file must be using `<ruby>` tags, that we don't support. Duplicate of #4868.

It alas does not really fit in our model of text layout, and it's very hard to do right:
https://www.thetype.com/2017/08/11606/ - [English translation](http://translate.google.com/translate?u=https://www.thetype.com/2017/08/11606/&hl=en&langpair=auto%7Cen&tbb=1&ie=UTF-8) (2nd half of the article).
And no active developper read CJK.

Btw, if you read japanese (unless you are just learning it) and have some taste for typography, could you have a look at #6162 (with some answers maybe :).

(It is advertized just above the New issue button you hit :/ )
<kbd>![image](https://user-images.githubusercontent.com/24273478/83561669-86590300-a518-11ea-9fec-68762aff30c5.png)</kbd>

**Comment by Geniusssmit** [comment]
> Technically, that doesn't happen automagically with any text.
> Your source file must be using `<ruby>` tags, that we don't support. Duplicate of #4868.
> 
> It alas does not really fit in our model of text layout, and it's very hard to do right:
> https://www.thetype.com/2017/08/11606/ - [English translation](http://translate.google.com/translate?u=https://www.thetype.com/2017/08/11606/&hl=en&langpair=auto%7Cen&tbb=1&ie=UTF-8) (2nd half of the article).
> And no active developper read CJK.
> 
> Btw, if you read japanese (unless you are just learning it) and have some taste for typography, could you have a look at #6162 (with some answers maybe :).
> 
> (It is advertized just above the New issue button you hit :/ )
> ![image](https://user-images.githubusercontent.com/24273478/83561669-86590300-a518-11ea-9fec-68762aff30c5.png)

I see, too bad.. on pocketbook only koreader can handle japanese highlights and dictionaries properly, but that's not enough for pleasurable reading. About typography, sorry I don't feel proficient enough to answer those questions

**Comment by Geniusssmit** [comment]
![IMG_20200603_011547](https://user-images.githubusercontent.com/24941285/83575427-1a869280-a538-11ea-9bfe-25b28435f45d.jpg)
Looks like that on some books, maybe it's possible?

**Comment by poire-z** [comment]
> Looks like that on some books, maybe it's possible?

Smaller and on the side?

Do you mean:
A) it looks like on your picture **with KOReader** - and you hope that having it smaller would help moving it above the previous word? Answer: no

or

B) it looks like on your picture **with another reader** than KOReader? And you'd like to have it the same way with KOReader? Answer: possible.

For B), assuming the source test is like:
```html
<ruby>
漢 <rp>(</rp><rt>kan</rt><rp>)</rp>
字 <rp>(</rp><rt>ji</rt><rp>)</rp>
</ruby>
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rt
(highlight some text before/after such construct, hit View HTML and post a pic if the following does not work).
you could get the text smaller with a style tweak (or we could make it global in our epub.css, but first try it as a style tweak)

Create `koreader/styletweak/smaller_ruby_text.css` with:
```css
rt { font-size: 70%; }
```
And enable it via the menu, see https://github.com/koreader/koreader/wiki/Style-tweaks
(You could even change the font used, the color or give it a background-color...)

**Comment by Geniusssmit** [comment]
> Create `koreader/styletweak/smaller_ruby_text.css` with:
> 
> ```css
> rt { font-size: 70%; }
> ```

Wow, that worked very well, now it's readable!
Is it possible to ignore ruby text when highlighting? If it is, looking up words should be easy.

**Comment by poire-z** [comment]
> Is it possible to ignore ruby text when highlighting

No, not that easily, that would need some coding on the crengine side (as on the KOReader side, we don't know what tags the text comes from).

Just by curiosity (and for thoughts), could you show the HTML for these exact (or equivalent) snippets ?
![image](https://user-images.githubusercontent.com/24941285/83559592-7db6fb80-a51d-11ea-83fe-ea4c1c19e4ed.png) ![image](https://user-images.githubusercontent.com/24941285/83559720-b9ea5c00-a51d-11ea-9bf5-8aea3a439803.png)
First has 3 little chars above 2 letters, making the 2 letters kinda like a single word - second has 2 chars above each letter, so each letter could be a word or both make a single word with the 4 littles chars associated with each word. Seeing the sources should answer that.

**Comment by Geniusssmit** [comment]
> > Is it possible to ignore ruby text when highlighting
> 
> No, not that easily, that would need some coding on the crengine side (as on the KOReader side, we don't know what tags the text comes from).
> 
> Just by curiosity (and for thoughts), could you show the HTML for these exact (or equivalent) snippets ?
> ![image](https://user-images.githubusercontent.com/24941285/83559592-7db6fb80-a51d-11ea-83fe-ea4c1c19e4ed.png) ![image](https://user-images.githubusercontent.com/24941285/83559720-b9ea5c00-a51d-11ea-9bf5-8aea3a439803.png)
> First has 3 little chars above 2 letters, making the 2 letters kinda like a single word - second has 2 chars above each letter, so each letter could be a word or both make a single word with the 4 littles chars associated with each word. Seeing the sources should answer that.

I don't know how to do that. Look at these gifs, maybe you will get the idea
![rp1tJaApEv](https://user-images.githubusercontent.com/24941285/83646226-0ab09200-a5bc-11ea-84f2-69cd96541c6a.gif)
![FkZnd9Imel](https://user-images.githubusercontent.com/24941285/83646236-0e441900-a5bc-11ea-91b9-4ebe2a02fa7e.gif)


躊躇う is 1 word and it's reading is ためらう
融通 is also 1 word and reading is ゆうづう

**Comment by poire-z** [comment]
Do the same thing on KOReader (even if it is displayed on the same line), and select `View HTML` in the highlight popup. You should probably see some `<ruby> ... </ruby>`, one or two, with the bits inside in other `<rb>` or `<rt>` tags.
That's what I'm interested to see (even if your gifs give me an idea of what to expect, thanks :)

(Why does it sometimes select _half_ the glyph on the 2nd animated gif ?

**Comment by Geniusssmit** [comment]
> Do the same thing on KOReader (even if it is displayed on the same line), and select `View HTML` in the highlight popup. You should probably see some `<ruby> ... </ruby>`, one or two, with the bits inside in other `<rb>` or `<rt>` tags.

![IMG_20200603_182403](https://user-images.githubusercontent.com/24941285/83655925-9bd93600-a5c7-11ea-84c6-9e07b7147a1c.jpg)
![IMG_20200603_182339](https://user-images.githubusercontent.com/24941285/83655991-ad224280-a5c7-11ea-8547-f0062eb036bd.jpg)

> (Why does it sometimes select _half_ the glyph on the 2nd animated gif ?

I don't know, seems like thats how highlighting works on ruby

**Comment by poire-z** [comment]
Thanks, that's exactly it.
This one is for the (1 big glyph + 2 small above) + (1 big glyph + 2 small above).
Can you show me the same for (2 big glyphs + 3 small above) ? (I guess you'll have to guess as we don't show it above :) but it should show as 2 big glyphs + 3 small after :)

**Comment by Geniusssmit** [comment]
> Thanks, that's exactly it.
> This one is for the (1 big glyph + 2 small above) + (1 big glyph + 2 small above).
> Can you show me the same for (2 big glyphs + 3 small above) ? (I guess you'll have to guess as we don't show it above :) but it should show as 2 big glyphs + 3 small after :)

Different book
![IMG_20200603_184111](https://user-images.githubusercontent.com/24941285/83657896-29b62080-a5ca-11ea-80c3-d9eb5b0cc53c.jpg)

![IMG_20200603_184215](https://user-images.githubusercontent.com/24941285/83657869-1d31c800-a5ca-11ea-98e6-0253c728cfec.jpg)

**Comment by Geniusssmit** [comment]
As you can see sometimes there are 5 syllables on 2 "glyph" words

**Comment by poire-z** [comment]
OK, I see, thanks.
Do you think these "small glyphs" (above or after)  could be considered "cosmetics", like our list item bullets, and never be part of text selection ? (In Japanese but also in Chinese, where they can be latin text.) Not selectable = no dict or wikipedia lookup on them, no translation, no highlighting.

And how bearable / good enough is it to have them on the side and not on top/bottom?

Btw, in case you dont want to see them, use `rt { display: none; }` and they obviously won't be part of the lookup text :)

Anyway, thanks for the detailed screenshots, pics and source code. I'll keep that in mind and give it some thoughts over the summer - can't promise anything :)

**Comment by Geniusssmit** [comment]
> Do you think these "small glyphs" (above or after) could be considered "cosmetics", like our list item bullets, and never be part of text selection ?
Exactly

> And how bearable / good enough is it to have them on the side and not on top/bottom?
Honestly, it's a huge compromise. As you can see on my last photo it look ugly

> Btw, in case you dont want to see them, use `rt { display: none; }` and they obviously won't be part of the lookup text :)
Thanks, but that also rather big compromise, especially for learners. Sometimes furigana is absolutely necessary, for example in fantasy books.

> I'll keep that in mind and give it some thoughts over the summer - can't promise anything :)
Cool! looking forward to it

**Comment by poire-z** [comment]
I had a quick look at https://drafts.csswg.org/css-ruby/, and was horrified by the complexity and the amount of special handling:

> However ruby containers also establish a ruby formatting context that builds further structure around their segment of the inline formatting context. Ruby bases, ruby annotations, ruby base containers, and ruby annotation containers are internal ruby boxes: like internal table elements, they have specific roles in ruby layout, and participate in their ruby container’s ruby formatting context.

> The CSS model does not require that the document language include elements that correspond to each of these components. Missing parts of the structure are implied through the anonymous box generation rules similar to those used to normalize tables. 

So, it would need as much work as I did for "complete incomplete tables" in https://github.com/koreader/crengine/commit/bf1992c3fb9c69e98570a03deb664c667ae6585a , and probably more complex as this interact with the text formatting (unlike tables, where we are safe in the sane DOM and block rendering part of the code).

But reading:

> 	The structure of ruby is similar to that of a table: there are “rows” (the base text level, each annotation level) and “columns” (each ruby base and its corresponding ruby annotations).

I wondered if I could unleash the power of "complete incomplete tables" to make little inline-tables for each ruby, putting stuff above each other, just with CSS tweaks !

And after a morning of trying various stuff like:
```css
/* As inline-table, annotation below */
ruby {
    color: blue;
    text-align: center;
    text-indent: 0;
    display: inline-table;
    vertical-align: baseline;
    line-height: 0.8;
}
rt {
    color: red;
    text-align: center;
    display: table-row;
    vertical-align: bottom;
    font-size: 60%;
    line-height: 0.5;
}
/* As inline-table, single cell, annotation below */
ruby {
    color: blue;
    text-align: center;
    text-indent: 0;
    display: inline-table;
    vertical-align: baseline;
    line-height: 0.6;
}
rt {
    color: red;
    text-align: center;
    display: block;
    vertical-align: -100%;
    white-space: nowrap;
    font-size: 50%;
    line-height: 0.4;
}
/* As inline-table, 2 cells, annotation on the right */
ruby {
    color: blue;
    text-indent: 0;
    display: inline-table;
}
rt {
    color: red;
    display: table-cell;
    vertical-align: middle;
    width: 1em;
    line-height: 0.3em;
    font-size: 30%;
}
/* As inline-block, annotation below */
ruby {
    color: blue;
    text-align: center;
    text-indent: 0;
    display: inline-block;
    vertical-align: top;
}
rt {
    color: red;
    text-align: center;
    display: block;
    vertical-align: top;
    white-space: nowrap;
    font-size: 50%;
    line-height: 0.1;
}
```
(Keeping the above for reference).
And lots of time spent tuning line-height and vertical-align, for so-so result - and the annotation naturally below the text:
<kbd>![image](https://user-images.githubusercontent.com/24273478/83755813-6cc9cf80-a66e-11ea-8187-843fb4434288.png)</kbd>

I managed to get something looking quite nice when remembering crengine always shows a table caption at the top of the table. So, with:
```css
tabularBox { border: 1px solid green; }
/* As inline-table, annotation above via table caption*/
ruby {
    color: blue;
    text-align: center;
    text-indent: 0;
    display: inline-table;
    Zvertical-align: baseline;
    Zline-height: 0.8;
}
rt {
    color: red;
    text-align: center;
    display: table-caption;
    vertical-align: top;
    font-size: 0.5em;
    line-height: 0.8em;
}
```
We can generate something that is looking quite alright (except for the variable line-height for lines with ruby vs those without):
<kbd>![image](https://user-images.githubusercontent.com/24273478/83756249-11e4a800-a66f-11ea-9e82-761f44f01bfb.png)</kbd>

With some fix to table caption measurement, and a few new added `-cr-hint` to tweak text selection, we could get:

<kbd>![image](https://user-images.githubusercontent.com/24273478/83756896-fb8b1c00-a66f-11ea-9b45-ca4181f2243b.png)</kbd>

with:
```css
ruby {
    color: blue;
    text-align: center;
    text-indent: 0;
    display: inline-table;
    -cr-hint: text-selection-inline;
}
ruby tabularBox {
    -cr-hint: text-selection-inline;
}
rt {
    color: red;
    text-align: center;
    display: table-caption;
    vertical-align: top;
    font-size: 0.5em;
    line-height: 0.8em;
    -cr-hint: text-selection-skip;
}
rp {
    display: none;
}
```
(@Geniusssmit : you can try that one as a user styletweak - you'll have some issues when the annotation is larger than the base text, and you'll still get the annotation in the text selection - fix for that will have to wait a few days for next crengine update.)

Without colors:
<kbd>![image](https://user-images.githubusercontent.com/24273478/83757168-5e7cb300-a670-11ea-8d57-964bb76b9c9c.png)</kbd>

With increased Line Spacing:
<kbd>![image](https://user-images.githubusercontent.com/24273478/83757249-7c4a1800-a670-11ea-9ceb-1140695870e1.png)</kbd>

(I gave up playing with tuning `font-size`, `line-height` and `vertical-align`, but may be it's possible to get something better).

Is that good enough?
So that we don't explicitely have to support ruby, and people can tweak the rendering and layout themselves with such styletweaks.

Unfortunatly, it doesn't work with the sample from #4868, where multiple components are in the same `<ruby>` tag:
```html
<p><ruby>漢<rp>(</rp><rt>Kan</rt><rp>)</rp>
字<rp>(</rp><rt>ji</rt><rp>)</rp>
</ruby></p>
```
We'd get:
<kbd>![image](https://user-images.githubusercontent.com/24273478/83759671-2ecfaa00-a674-11ea-94f1-1e1af117584f.png)</kbd>
instead of:
<p><ruby>漢<rp>(</rp><rt>Kan</rt><rp>)</rp>
字<rp>(</rp><rt>ji</rt><rp>)</rp>
</ruby></p>

So, it's not a universal solution, but may be expert style tweakers will find a solution to handle their specific case in the same way.
