### ISSUE TITLE
PNG Image Displayed as black box

### ISSUE THREAD

**Issue by zedth2** [koreader/koreader#6345]
* KOReader version: v2020.06
* Device: Kobo Forma
* FW Version: 4.22.15190 efcb227b40

#### Issue
Images in EPUB appear as black squares.

#### Steps to reproduce
Open EPUB? Though I've only tried one so far. ["Ansible for DevOps"](https://www.ansiblefordevops.com)

The book was provided by leanpub as an EPUB. The offending image is attached. 
![leanpub_key](https://user-images.githubusercontent.com/5951901/86492259-89275d80-bd3b-11ea-8e32-11c4329aa123.png)

Along with the CSS used in the book
```css
/* tips, warnings, etc */
aside.blurb {
  background-color: white;
  margin: 1em 1em 1em 0em;
  padding-left: 0;
  border-style: none;
  width: 80%; /* fallback */
  width: calc(100% - 60px);
  display: inline-block;
  padding-left: 60px;
  background-repeat: no-repeat;
  background-position: 0% 1em;
  background-size: 40px 40px;
}
aside.blurb.tip {
  background-image: url("images/leanpub_key.png");
}
```
Neither of the Style Images settings have any affect.
Checking "Pure black and white" causes no black box to appear and no image. But text is no longer covered and is now readable. So that's like mildly acceptable as a work around.

Here's a picture of the result. Though to be fair the Kobo reader SW just throws the images out all together. 
![2020-07-03 14 38 14](https://user-images.githubusercontent.com/5951901/86492206-5bdaaf80-bd3b-11ea-93a2-b838afd1b175.jpg)

If I'm missing something please let me know as this is my first ereader and first time using KOReader. I only just got it working a few hours ago.
