### ISSUE TITLE
Horizontal rule section with image embedded in CSS is displayed with gray background

### ISSUE THREAD

**Issue by wanders78746** [koreader/koreader#6632]
* KOReader version: 2020.08.1
* Device: Likebook Mars with Android 8.1

#### Issue
Horizontal rule section with image embedded in CSS is displayed with ugly gray background. Image associated with hr section is overlaid.

#### Steps to reproduce
See attached file Foo.epub in attached .zip file.

##### `crash.log` (if applicable)
N/A

##### Attachments
[Foo.zip](https://github.com/koreader/koreader/files/5177054/Foo.zip)

**Comment by pazos** [comment]
Can reproduce in Auto -> epub.css, but not with html5.css

![2020-09-05_01-17](https://user-images.githubusercontent.com/975883/92290795-b77d1100-ef15-11ea-8dfa-5245a0277856.png)
![2020-09-05_01-17_1](https://user-images.githubusercontent.com/975883/92290797-b946d480-ef15-11ea-9458-036470672728.png)

**Comment by poire-z** [comment]
In this book:
```css
hr.transition {
        background: url(../Images/image00083.jpeg) no-repeat center;
        height: 1em;
        border: none;
        margin: 1em 0em 0.50em 0em;
}
```
In our epub.css:
```css
hr {
    height: 2px;
    background-color: #808080;
    margin: 0.5em auto;
}
```
In our html5.css:
```css
hr {
  color: gray;
  border-style: inset;
  border-width: 1px;
  margin: 0.5em auto;
}
```
So it's our `background-color: #808080` that gets added to the image.

https://www.w3.org/TR/CSS2/sample.html :
```css
hr              { border: 1px inset }
```
Most browsers have `border: 1px inset`, some of them have additionally `color: gray`.

I don't like much border inset. With Zoom/DPI: 300:
With epub.css:
<kbd>![image](https://user-images.githubusercontent.com/24273478/92970536-1f37dc80-f47f-11ea-8392-30e2ced45b66.png)</kbd>
With html5.css:
<kbd>![image](https://user-images.githubusercontent.com/24273478/92970567-2d85f880-f47f-11ea-9a3c-b193e8d17f46.png)</kbd>

So, what should we go with instead in our epub.css ?
