### ISSUE TITLE
Line break at the footnote number

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#6718]
Shouldn't we avoid line breaks before the footnote numbers?
![Reader_2020-09-27_095627](https://user-images.githubusercontent.com/62179190/94358811-35af7c00-00ac-11eb-96cd-bdb4d0b1d282.png)

**Comment by Frenzie** [comment]
Possibly, but how is it marked up?

**Comment by hius07** [comment]
> how is it marked up?

a[type="note"]

**Comment by poire-z** [comment]
> Shouldn't we avoid line breaks before the footnote numbers?

For EPUBs I would say: we cant't know, publisher bug, not ours, let that to user style tweaks.
But for FB2, as we're somehow half the publisher, may be.

I met that kind of issue with some EPUB in https://github.com/koreader/crengine/pull/337#issuecomment-628465266.
and could solve it one month later with https://github.com/koreader/crengine/pull/337#issuecomment-639011542.

So, may be this is just enough?:
`a[type="note"]::before { content: "\2060" }`
It should prepend a https://en.wikipedia.org/wiki/Word_joiner at the start of the link. Dunno if that's enough to kill a break after the existing preceeding space.

**Comment by Frenzie** [comment]
Sorry, I meant for example by using the view HTML on selection feature. I'm not sure it's something that "should" be avoided unless the publisher has included a `white-space: no-wrap` in a surrounding element or some such though.

**Comment by hius07** [comment]
> by using the view HTML on selection feature.

![1](https://user-images.githubusercontent.com/62179190/94359750-9ee5be00-00b1-11eb-9298-13e207051942.png)

**Comment by hius07** [comment]
> a[type="note"]::before { content: "\2060" }

Yes, this works:
![Reader_2020-09-27_110638](https://user-images.githubusercontent.com/62179190/94359778-b6bd4200-00b1-11eb-8057-cdcf8e11fcd8.png)

**Comment by hius07** [comment]
> Dunno if that's enough to kill a break after the existing preceeding space.

I've inserted a space (32) before the footnote number and it does work as well.

**Comment by Commodore64user** [comment]
@poire-z I am having a similar issue on EPUB but inversed the break happens in the in-page footnote, only when using Bookerly, Noto Serif doesn't do this, please save my sanity.

<p align="center">
<img src="https://github.com/user-attachments/assets/48a1b0af-bf78-4acf-adf8-4c3b96995f23" width=80%> 
</p> 


```html
<aside epub:type="endnote" id="wre0004096en"><p><a class="backlink" href="chapter009.xhtml#wre0004096" 
role="doc-backlink">115.</a> <em>Zieten</em>: <span aria-label="1339" epub:type="pagebreak" id="pg1339" 
role="doc-pagebreak"/>Hans Ernst Karl von Zieten (1770–1848) commanded the Prussian 1st Corps.</p></aside>

<aside epub:type="endnote" id="wre0004101en"><p><a class="backlink" href="chapter009.xhtml#wre0004101" 
role="doc-backlink">116.</a> <em>Friant, Michel, Roguet, Harlet, Mallet, Poret de Morvan</em>: General Comte 
Louis Friant (1758–1829), in command of the grenadier division of the Imperial Guard; General Comte Claude-Étienne 
Michel (1772–1815), second-in-command of the chasseur division, fatally wounded in the battle; General Comte 
François Roguet (1770–1846), second-in-command of the grenadier division; General Baron Louis Harlet (1772–1853) 
of the 4th Regiment of Grenadiers; Colonel Chevalier Pierre Antoine-Anselme Mallet (1778–1815), in command of the 
3rd Regiment of Chasseurs, fatally wounded at Waterloo; General Baron Paul Poret de Morvan (1777–1834) of the 3rd 
Regiment of Grenadiers.</p></aside>
```

```css
a.backlink {
	border-bottom: 0px;
	font-size: 0.85em;
	font-style: normal;
	padding: 0 1em 0.2em 0;
	text-align: left;
	text-decoration: none;
	text-indent: 0;
}
.note_chapterheader {
	font-size: 1.1em;
	font-weight: normal;
	text-align: left;
}
.endnote_wrapper p {
	text-indent: 0em;
	margin-bottom: 0.3em;
}
.endnote_wrapper .backlink, .footnote_wrapper .backlink {
	display: inline-block;
	margin-left: -2em;
	padding: 0;
	width: 2em;
}
```

**Comment by poire-z** [comment]
As it happens only with footnote numbers >= 100, which are wider than 2-digits ones like 99, I would say that with some fonts, `100` is wider than `2em` and gets wrapped to `10↵0.`
You can try book'style'tweaking: `.endnote_wrapper .backlink, .footnote_wrapper .backlink { width: 2.5em !important; }`.
Or `width: auto` so they are sized to their content, but footnote 99 and footnote 100 won't have their text left edge aligned.

Why the push down of the paragraph text: the inline-block gets this width, and, in its paragraph, gets aligned (per-specs) to the baseline of its _last_ line, so you get
```
10
0.  The paragraph text...
```
You can try (just for fun - without the previous one) `.endnote_wrapper .backlink, .footnote_wrapper .backlink { display: inilne-table !important; }` which should align it to the baseline of its _first_ line instead.

**Comment by Commodore64user** [comment]
Following up on your reasoning of 2em being too tight, i tried this and that seems to be enough space for it now. So i checked the Amazon reader, and with Bookerly, it doesn’t seem to suffer the same fate, I suppose they perhaps ignore some of the css or do some magic to avoid all this nonsense. Penguin, it’s always their books i have the most exasperating experience with, why won’t they hire you to fix their shite formatting?

```css
.endnote_wrapper p, .footnote_wrapper p {
    padding-left: 3em;
}
a.backlink {
    width: 3em !important;
    margin-left: -3em !important; 
}
```
