### ISSUE TITLE
FR: Support fixed layout ePub

### ISSUE THREAD

**Issue by alessionossa** [koreader/koreader#6742]
I tried to open a fixed layout ePub on an Onyx Boox Note2, but KO reflows the content, making it unreadable.

It would be useful if KO supported fixed layout, especially for the growing number of large-screen eink devices.

**Comment by NiLuJe** [comment]
Easier said than done.

Whatever support may come, it'll be contingent on MµPDF's own support of FXL.

I have no idea in which state said support currently is ;).

**Comment by poire-z** [comment]
No current support in our crengine.
I don't know much about fixed layout, but I think I once read about it and it might be a matter of some specific info in the epub metadata, and the heavy use of `position:absolute` and `position:relative` (and associated `top/left/right/bottom`) in the HTML fragments.
crengine has currently no support for the CSS `position/top/left/right/bottom` properties.

(It might not be such heavy work to add support for position: in crengine, as when we're rendering the document, we position an element relative to its parent, so it might just be a matter of shifting these relative to some other reference than their parent and the values from the position/top/left.. properties... but it's another matter to handle that for page breaks, deciding what to draw, managing overflows... :) so, no plan on adding this - and I never met a fixed layout EPUB that I wanted to read :)

**Comment by ezdiy** [comment]
It's epub3 spec, and it's pure evil, just `<display_options><option name="fixed-layout">true</option></display_options>` in header. The stuff is used for scanned pages and what not, essentially what djvu/pdf does already.

It's an utter feature bloat in epub, as there was never need for this when it comes to actual ebooks (don't confuse with pre-pagination which can be useful, for instance comics stored in epub). I don't think we support epub3 features at all for that matter. People should just stick with djvu or pdf for scanned documents.

**Comment by alessionossa** [comment]
@ezdiy If so, I am referring to pre-paginated and yes, PDF already does this.

Only one thing to correct in your statement: `<option name="fixed-layout">true</option>` is specific for some proprietary formats, as you can see at http://idpf.org/epub/fxl/#mappings .

The book was given to me in this format, and to use it, I am building a little program to convert fxl ePub to PDF.

**Comment by ezdiy** [comment]
If you just want *actual* pre-pagination, width="100%" height="100%" still works in epub2. It's the *real* fixed positioning modes of viewport/viewbox where it's no longer just pre-paginated, but full on pdf-esque typeset. The amazon proprietary alias doesn't matter, it's the same thing as in epub3. The moment you fixed-size anything, you're hosed.

**Comment by poire-z** [comment]
Not strictly fixed text layout related, but about @ichnilatis-gr issue at https://www.mobileread.com/forums/showthread.php?t=340264 : 

(Pinging @Jellby as you seem to be the publisher of this book :)

This EPUB uses a few hacks to get the intended effect. It has a few invisible blocks, floats, and some with `position: relative` that we don't support - but it looks like it's not mainly via these that it achieves the end result.
It's via `height` and negative vertical margins, in the included wrap.css (there's a nowrap.css that is not used but looks more friendly :).

With this HTML : 
```html
<h1 class="chapter">CHAPTER I</h1>

<div class="chapter-head" id="ch1">
  <div class="picture">
    <img src="images/Illustration-002.jpg" alt="CHAPTER I."/>
  </div>
  <div class="top">
    <img src="images/auximg-002a.png" alt=""/>
  </div>
  <div class="middle">&nbsp;</div>
  <div class="bottom">
    <img src="images/auximg-002b.png" alt="Tom at Home."/>
  </div>
</div>

<p><span class="first-word">&ldquo;Tom!&rdquo;</span>&nbsp;</p>
```
It uses this twisted CSS (possibly clever, but still twisted :):
```css
span.first-word {
  display: none;
}

div.chapter-head img {
  width: 100%;
}
div.chapter-head div {
  text-align: left;
  margin: 0 3px 0 0;
}
div.chapter-head div.picture {
  width: 100%;
  height: 4em; /* me: the picture is taller than this */
  margin: 0 0 -4em 0; /* me: make the picture overrides the previous H1 */
  overflow: visible;
}
div.chapter-head div.top,
div.chapter-head div.middle,
div.chapter-head div.middle2,
div.chapter-head div.bottom {
  /* hide as much as possible */
  position: relative;
  z-index: -1;
  visibility: hidden;
  opacity: 0;
}
div.chapter-head div.top {
  float: none;
  width: 100%;
  margin-bottom: -1em;
}
div.chapter-head div.middle,
div.chapter-head div.middle2 {
  float: left;
  clear: both;
  height: 1em;
  line-height: 1;
  margin-right: 0.75em;
}
div.chapter-head div.bottom {
  float: left;
  clear: both;
}

div#ch1 div.middle {
  width: 68.47%; /* 406/593 */
}
div#ch1 div.bottom {
  width: 50.08%; /* 297/593 */
}
```

It's the `height: 4em` that should make the following text start "inside" the picture: the picture has some blank space on its right so the text can be drawn over it, and floats are used so the text does not override the left part of the picture that is not blank.

crengine, originally and also with #5117, only ensures `height:` when it's larger than the height used by the inner content, in which case it adds some blank space after the inner content to ensure the requested height. It (as a feature) does not go back overriding the inner content with the next block if there is a smaller `height` specified (because this could feel like an error and could mess page splitting):
https://github.com/koreader/crengine/blob/844be50324fb7ddd7849bca04a191803f264f237/crengine/src/lvrend.cpp#L7893-L7906

There's just one case where we "go back": with negative top/bottom margins, because we expect them to be small and the "going back" and page-break avoidance it requires shouldn't hurt too much.

If I fake the support for smaller height by manually adding a large negative bottom margin:
```css
div.chapter-head div.picture {
  width: 100%;
  height: 4em;
                          margin-bottom: -38em; /* needed a few tries to find this value */
  overflow: visible;
}
```
we can get the expected effect:
![image](https://user-images.githubusercontent.com/24273478/124354511-a3c13a80-dc0c-11eb-9036-e2920238800e.png)

(If I change my geometry a bit it can get messy:
![image](https://user-images.githubusercontent.com/24273478/124354550-d834f680-dc0c-11eb-8a38-ae14dad877a4.png)
dunno if proper height: support instead of my margin-bottom hack would make it work in all cases.)

Anyway, dunno how much we need to support these smaller heights (and how much this is not enough in many other cases of such tweaks to get that kind of effect), vs. the negative effects it might have on content with badly specified dimensions. (OK, we support negative margins in "web" mode, so we could support more risky stuff like smaller heights, we would still have "book" mode to get out of the mess, but still :)
