### ISSUE TITLE
FR/Tweak help: Shade every other line of text

### ISSUE THREAD

**Issue by fabricalado** [koreader/koreader#7392]
It's pretty much [this](https://www.reddit.com/r/css/comments/jke15e/how_do_i_shade_every_other_line_of_text_in_an/), but for KOReader ebooks.

I tried tweaking with the CSS, but no response. Any ideas?

**Comment by Frenzie** [comment]
I can't think of anything supported by crengine that could dynamically do that otoh. But perhaps a repeating background the height of two lines would do the trick?

**Comment by fabricalado** [comment]
Sounds like it, but whenever I try [this code](https://www.reddit.com/r/css/comments/jke15e/how_do_i_shade_every_other_line_of_text_in_an/gaj9l2r/?utm_source=reddit&utm_medium=web2x&context=3) on the book-specific tweaks:
body {
   line-height: 1.5rem !important;
   background-image: repeating-linear-gradient(
    white,
    white 1.5rem,
    #e8e8e8 1.5rem,
    #e8e8e8 3.0rem
  );
}
, all it seems to do is to change the line spacing!

**Comment by Frenzie** [comment]
I'm suggesting the equivalent of that, but pretend linear-gradient is not supported. ;)

**Comment by poire-z** [comment]
We don't support anything gradient or calc() that could help having that done easily.

The best you can do is prepare yourself an image with the top half in one color and the bottom half in another (here, I'm using one showing a landscape, light blue above the horizon, darker below, horizon somehow in the middle), and use something like:

```css
p {
  padding-top: 0 !important;
  line-height: 1.5em !important;
  background-size: 100% 3em; /* twice the above */
  background-repeat: repeat;
  background-position: top left;
  background-image: url("Lac_sevan_armenie.png");
}
```

and you could get:
<kbd>![image](https://user-images.githubusercontent.com/24273478/110221072-4c16fa80-7eca-11eb-9440-44f40e3fec49.png)</kbd>

With 3em and 6em:
<kbd>![image](https://user-images.githubusercontent.com/24273478/110221047-238f0080-7eca-11eb-8d94-d52fad48e0a4.png)</kbd>
