### ISSUE TITLE
font-variant display

### ISSUE THREAD

**Issue by roger64** [koreader/koreader#7913]
* KOReader version:2021.06
* Device:Kindle PW3

 On this attached _scrambled_ ePub3, I have used open-type "font-variant:small-caps" for the two following styles _Heading_ and _Subtitle_ (see page in chapitre 4.xhtml).

I also used "font-variant:normal" for a span within these styles (see styles.css).

Code:
```css
.Heading span {
  display: block;
  margin-top: 0.25em;
  font-size: 0.85em;
  font-style: italic;
  font-variant: normal;
  color: #585858;
}
.Subtitle span {
  display: block;
  margin-top: 0.25em;
  font-size: 0.9em;
  font-family: LinLibertineG30;
  font-style: italic;
  font-variant: normal;
}
```
The resulting display with Calibre and Sigil are OK (see screenshot)
With Koreader, I get italic with small-caps which is not intended.

![font-variant-calibre](https://user-images.githubusercontent.com/1344670/123963235-d7ba1700-d9e4-11eb-904c-4bf73cabbec3.png)
[scrambled.zip](https://github.com/koreader/koreader/files/6740965/scrambled.zip)
