### ISSUE TITLE
Koreader crashes when opening specific ebook

### ISSUE THREAD

**Issue by beelzebielsk** [koreader/koreader#8417]
* KOReader version: 2021.10.1
* Device: Onyx Boox Poke 2

#### Issue

Koreader is crashing when opening a specific ebook. Other ereaders aren't crashing when opening it. It's crashing on both my desktop and android device, tho I'm only reporting for the android device.

#### Steps to reproduce

Open the specific ebook.

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/7472677/crash.log)

**Comment by NiLuJe** [comment]
We're going to need a [scrambled](https://www.mobileread.com/forums/showthread.php?t=267998) copy of the book in question to reproduce.

(Assuming it does reproduce in a scrambled copy, if not, try to contact one of us privately in Gitter or on MobileRead).

**Comment by beelzebielsk** [comment]
It does not reproduce in a scrambled copy.

**Comment by poire-z** [comment]
(@NiLuJe has sent me your original copy.)

The crash is caused by the combination of:

000_Cover.xml having:
```html
<body style="margin:0; padding:0; font-size:0;">   <!-- this font-size:0 -->
whatever
</body>
```
and the CSS it uses having:
```css
@font-face {
 font-family: "Minion";
 font-weight: normal;
 font-style: normal;
 src: url('font/MinionPro-Regular.otf');
 }
body{
 font-family:"Minion";  /* this referencing an existing embedded font, defined above */
 text-align: justify;
 color: #000000;
}
```
and the code getting in there:
```
    if ( pstyle->font_family == css_ff_inherit ) {
        //UPDATE_STYLE_FIELD( font_name, "" );
        // Just set the name of the font already resolved (via enode->initNodeFont)
        // for the parent node
        pstyle->font_name = parent_font.get()->getTypeFace();
    }
```
and finding parent_font being NULL and crashing.

Change any of the conditions mentionned above, and no crash.

This solves the crash:
```diff
--- a/crengine/src/lvrend.cpp
+++ b/crengine/src/lvrend.cpp
@@ -10094,5 +10094,8 @@ void setNodeStyle( ldomNode * enode, css_style_ref_t parent_style, LVFontRef par
         // Just set the name of the font already resolved (via enode->initNodeFont)
         // for the parent node
-        pstyle->font_name = parent_font.get()->getTypeFace();
+        if ( !parent_font.isNull() )
+            pstyle->font_name = parent_font.get()->getTypeFace();
+        else
+            pstyle->font_name = "";
     }
     UPDATE_STYLE_FIELD( font_family, css_ff_inherit );
```

But I'm not sure what was happening :) so needs a bit more investigation.
