### ISSUE TITLE
FR: Support cursor:help

### ISSUE THREAD

**Issue by rkosov** [koreader/koreader#8801]
On Wikisource, many texts use cursor help or tooltip to display additional text in a pop-up window. The generated code looks like this:

`</p><p><i>Sam</i>. I strike quickly, being <span style="[cursor:help; border-bottom:thin dotted cornflowerblue;]()" title="[exasperated]()">moved</span>.`

However, koreader does not render this text. A proper implementation would show a small pop-up window when the user clicks/presses on the word. 

I can see this conflicting with the dictionary/highlighting feature. Maybe, it would be possible to use a short-press for the pop-up window and a long-one for the dictionary/highlight?

**Comment by NiLuJe** [comment]
Million dollar question: is this even supposed to be supported at all in an ePub context?

**Comment by Frenzie** [comment]
Probably not, but in theory treating the title attribute as a footnote could make quite a bit of sense. EPUB aside, it'll be in plenty of saved webpages.

**Comment by poire-z** [comment]
Probably not easy to handle them as in-page footnotes (would need to be display:block).
Dunno about popup footnotes - but it feels quite source specific, so not fond of hardcoding anything.

But you can help yourself with a style tweak to make the title visible (if you don't mind getting the wrapping `[...][)` crap displayed:

![image](https://user-images.githubusercontent.com/24273478/153682586-78127e25-3eb8-494b-ac32-136ee3c1ed9c.png)
with:
```css
*[title]::after {
    content: attr(title); /* one of the rare fancy content: stuff we support */
    font-size: 80%;
    vertical-align: super;
    color: blue
}
```
(Can't think of anything fancier, no way to use ruby (#6305) for those, no success with quick tries with inline-block.)

**Comment by poire-z** [comment]
Fancier alternative (I remembered my first attempt at hacking ruby via css :), if you don't mind the irregular line height:

![image](https://user-images.githubusercontent.com/24273478/153687900-7b701230-7aa0-4b42-835f-6065b644b2a0.png)

```css
*[title] {
  display: inline-table;
  text-indent: 0;
  line-height: 0.5em;
  text-align: center;
}
*[title]::after {
  content: "\A" attr(title);
  white-space: pre;
  font-size: 50%;
  color: blue;
}
```
