### ISSUE TITLE
Background and color are not rendered

### ISSUE THREAD

**Issue by bunglegrind** [koreader/koreader#8814]
* KOReader version: latest
* Device: Android 11 on OPPO A52 and Kobo Aura One

#### Issue 
I've recently bought the book "practical vim". The book frequently highlight some content (cursor, selection, etc...) by means of the background and color attributes. The ePub version both on Aura One and Android does not show any text highlighted.
I couldnt find any issues related. 

#### Steps to reproduce

Open the sample

[test.zip](https://github.com/koreader/koreader/files/8083904/test.zip)

**Comment by poire-z** [comment]
crengine (the epub renderer) does not support colors expressed with `rgb(a,b,c)`.
```css
span.shade-bg-magenta {
  background-color: magenta;
}
span.shade-bg-cyan {
  background-color: cyan;
}
span.shade-bg-light {
  background-color: rgb(220,220,180);
}
span.shade-bg-dark {
  background-color: rgb(50,50,100);
}
```
The 2 first ones works, the 2 last ones don't.

Until this gets supported (no promise, dunno how tricky the parsing could be), you can help yourself with a user style tweak, translating the few ones with rgb() to their # equivalents:
```css
span.shade-bg-light {
  background-color: #323264;
}
span.shade-bg-dark {
  background-color: #DCDCB4;
}
```
