### ISSUE TITLE
Support for transparency

### ISSUE THREAD

**Issue by bunglegrind** [koreader/koreader#8991]
* KOReader version: [v2022.03.1](https://github.com/koreader/koreader/releases/tag/v2022.03.1)
* Device: Kobo Aura One

#### Issue
It's in the middle between a feature request and a bug...in the latest version, support for rgb()/rgba() was added. 
https://github.com/koreader/koreader/pull/8916

Now rgba(0,0,0,0) is rendered as black instead of...nothing, I suppose because the engine doesn't support the alpha channel.

**Comment by poire-z** [comment]
Support for alpha should now be in, since #8972 / https://github.com/koreader/crengine/pull/474.
So, can you check with a nightly (or update to dev channel from KOreader) that it's ok ?
(Did this really happen in a book ? Using fully transparent colors ? In which context is it used for ?)

**Comment by bunglegrind** [comment]
OK, I will update to dev channel. I'll let you know. BTW, That value is retrieved from Firefox: getComputedStyle (I'm exporting html pages with save-as-ebook plugin) which returns rgba(0, 0, 0, 0)  in various circumstances

**Comment by bunglegrind** [comment]
Ok, using 2022.03.1-18 is quite better. However, there are some places in which trasparency is still not rendered properly.
[transparency - transparency.zip](https://github.com/koreader/koreader/files/8471665/transparency.-.transparency.zip)

**Comment by poire-z** [comment]
You could have been more helpful and told a bit more of what I should look at and see vs. what is expected :/

I see a black bar in your attachment.
I see a single HTML file with no text:
```html
  <body>
    <div>
      <div class="oq322">
        <div class="ul323"/>
        <div class="rV324"/>
        <div class="yg325"/>
        <div class="nr22">
          <div class="nr22"/>
        </div>
      </div>
      <div class="nr22"/>
    </div>
  </body>
```
and I see a 15000 bytes single-line CSS that you let me try to make readable - and i'm not going to dig in to _guess_ what it should do.

```css
.oq322 {
	background-color: rgb(255, 255, 255);
	border-top-width: 1px;
	border-top-style: solid;
	border-top-color: rgb(204, 204, 204);
	border-bottom-width: 1px;
	border-bottom-style: solid;
	border-bottom-color: rgb(204, 204, 204);
	border-right-width: 1px;
	border-right-style: solid;
	border-right-color: rgb(204, 204, 204);
	border-left-width: 1px;
	border-left-style: solid;
	border-left-color: rgb(204, 204, 204);
	border-collapse: separate;
	color: rgb(51, 51, 51);
	font-style: normal;
	font-variant: normal;
	font-weight: 400;
	font-size: 1.0em;
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	line-height: 1.4;
	list-style: outside;
	margin-top: 0px;
	margin-bottom: 0px;
	margin-right: 0px;
	margin-left: 0px;
	padding-top: 0px;
	padding-bottom: 0px;
	padding-right: 0px;
	padding-left: 0px;
	text-align: start;
	white-space: normal;
	display: block;
}

.ul323 {
	background-color: rgb(255, 255, 255);
	border-top-width: 0px;
	border-top-style: none;
	border-top-color: rgb(51, 51, 51);
	border-bottom-width: 0px;
	border-bottom-style: none;
	border-bottom-color: rgb(51, 51, 51);
	border-right-width: 0px;
	border-right-style: none;
	border-right-color: rgb(51, 51, 51);
	border-left-width: 0px;
	border-left-style: none;
	border-left-color: rgb(51, 51, 51);
	border-collapse: separate;
	color: rgb(51, 51, 51);
	font-style: normal;
	font-variant: normal;
	font-weight: 400;
	font-size: 1.0em;
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	line-height: 1.4;
	list-style: outside;
	margin-top: 0px;
	margin-bottom: 0px;
	margin-right: 0px;
	margin-left: 0px;
	padding-top: 0px;
	padding-bottom: 0px;
	padding-right: 0px;
	padding-left: 0px;
	text-align: start;
	white-space: normal;
	display: block;
}

.rV324 {
	background-color: rgba(0, 0, 0, 0);
	border-top-width: 11px;
	border-top-style: solid;
	border-top-color: rgba(0, 0, 0, 0);
	border-bottom-width: 11px;
	border-bottom-style: solid;
	border-bottom-color: rgba(0, 0, 0, 0);
	border-right-width: 11px;
	border-right-style: solid;
	border-right-color: rgba(0, 0, 0, 0);
	border-left-width: 11px;
	border-left-style: solid;
	border-left-color: rgba(0, 0, 0, 0);
	border-collapse: separate;
	color: rgb(51, 51, 51);
	font-style: normal;
	font-variant: normal;
	font-weight: 400;
	font-size: 1.0em;
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	line-height: 1.4;
	list-style: outside;
	margin-top: -11px;
	margin-bottom: 0px;
	margin-right: 0px;
	margin-left: 0px;
	padding-top: 0px;
	padding-bottom: 0px;
	padding-right: 0px;
	padding-left: 0px;
	text-align: start;
	white-space: normal;
	display: block;
}

.yg325 {
	background-color: rgba(0, 0, 0, 0);
	border-top-width: 10px;
	border-top-style: solid;
	border-top-color: rgba(0, 0, 0, 0);
	border-bottom-width: 10px;
	border-bottom-style: solid;
	border-bottom-color: rgba(0, 0, 0, 0);
	border-right-width: 10px;
	border-right-style: solid;
	border-right-color: rgba(0, 0, 0, 0);
	border-left-width: 10px;
	border-left-style: solid;
	border-left-color: rgba(0, 0, 0, 0);
	border-collapse: separate;
	color: rgb(51, 51, 51);
	font-style: normal;
	font-variant: normal;
	font-weight: 400;
	font-size: 1.0em;
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	line-height: 1.4;
	list-style: outside;
	margin-top: -10px;
	margin-bottom: 0px;
	margin-right: 0px;
	margin-left: 0px;
	padding-top: 0px;
	padding-bottom: 0px;
	padding-right: 0px;
	padding-left: 0px;
	text-align: start;
	white-space: normal;
	display: block;
}

.nr22 {
	background-color: rgba(0, 0, 0, 0);
	border-top-width: 0px;
	border-top-style: none;
	border-top-color: rgb(51, 51, 51);
	border-bottom-width: 0px;
	border-bottom-style: none;
	border-bottom-color: rgb(51, 51, 51);
	border-right-width: 0px;
	border-right-style: none;
	border-right-color: rgb(51, 51, 51);
	border-left-width: 0px;
	border-left-style: none;
	border-left-color: rgb(51, 51, 51);
	border-collapse: separate;
	color: rgb(51, 51, 51);
	font-style: normal;
	font-variant: normal;
	font-weight: 400;
	font-size: 1.0em;
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	line-height: 1.4;
	list-style: outside;
	margin-top: 0px;
	margin-bottom: 0px;
	margin-right: 0px;
	margin-left: 0px;
	padding-top: 0px;
	padding-bottom: 0px;
	padding-right: 0px;
	padding-left: 0px;
	text-align: start;
	white-space: normal;
	display: block;
}
```
So, a lot of unrelated crap, some negative margins, some imbricated empty blocks, no text.
This might be some crappy context that navigators are ok with, but crengine might not be.

So, show me a smaller and clean sample that exhibits some transparency issue - or some other non-transparency unrelated issue - but I'm not fighting with the above :)
