### ISSUE TITLE
Odd handling of jpg in SVG

### ISSUE THREAD

**Issue by lightmaster** [koreader/koreader#9766]
* KOReader version: 2022.10
* Device: Kobo

#### Issue
Odd handling of linked images within SVG, producing grey lines that file the `<div>` container holding the SVG. Can show up above/below or left/right of the image depending on the size of the `<div>` container.
#### Steps to reproduce
<details>
  <summary>stylesheet.css</summary>

```css
div.imagefp {
  text-align: center;
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  margin: 0;
  padding: 0;
  font-size: 0;
  page-break-before: always;
  page-break-inside: avoid;
  page-break-after: always;
}
```
</details>
<details>
  <summary>HTML code</summary>

```xml
<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="en">

<head>
  <title>Fire &amp; Blood</title>
  <link href="../styles/stylesheet.css" rel="stylesheet" type="text/css"/>
</head>

<body>

  <div class="imagefp">

    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100%" height="100%" viewBox="0 0 200 300">
      <image width="100%" height="100%" xlink:href="../images/img_0001.jpg"/>
      <!-- alt="Image" -->
    </svg>

  </div>

</body>

</html>
```
</details>

![Screenshot 2022-11-09 014245](https://user-images.githubusercontent.com/5307827/200758598-d58c2c88-638e-4019-8af8-06a050192a33.png)

##### `crash.log` (if applicable)
Not sure if I need a `crash.log`, will obtain one if needed.
